defaults: &defaults
  app_name: "Milog"
  domain: "milog.jimcheung.me:3000"
  https: false

development: 
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  domain: "milog.jimcheung.me"
